# API Configuration. Get free gemini api key @ https://aistudio.google.com/api-keys and replace your key here. No space, no quotes
GEMINI_API_KEY=your_api_key_here
MODEL_NAME=gemini-2.5-flash

# Rate limiting (seconds between requests)
REQUEST_DELAY=2

# URLs to scrape (multiple urls comma-separated. Avoid pages with lot of content on free tier )
URLS=https://en.wikipedia.org/wiki/Artificial_intelligence

# Vector store settings
CHUNK_SIZE=1000
CHUNK_OVERLAP=200
